# Generated by Django 4.2.4 on 2023-08-22 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('air_date', models.CharField(max_length=150)),
                ('episode', models.IntegerField()),
                ('characters', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('dimension', models.CharField(max_length=150)),
                ('residents', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead')], default='unknown', max_length=150)),
                ('species', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Genderless', 'Genderless')], default=' unknown', max_length=150)),
                ('image', models.CharField(max_length=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('episodes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='main.episode')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='main.location')),
            ],
        ),
    ]
