# Generated by Django 4.2.4 on 2023-08-22 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characters',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='main.location'),
        ),
        migrations.AlterField(
            model_name='characters',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Genderless', 'Genderless'), ('Unknown', 'Unknown')], max_length=150),
        ),
        migrations.AlterField(
            model_name='characters',
            name='status',
            field=models.CharField(choices=[('Alive', 'Alive'), ('Dead', 'Dead'), ('Unknown', 'Unknown')], max_length=150),
        ),
    ]
