# Generated by Django 5.0.5 on 2024-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vendas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'P'), ('A', 'APROVADO'), ('R', 'RECUSADO'), ('C', 'CANCELADO')], max_length=30),
        ),
    ]
