# Generated by Django 4.2.4 on 2023-10-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='Telefone',
            field=models.IntegerField(),
        ),
    ]
