# Generated by Django 4.2.4 on 2023-10-04 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(choices=[('Moto', 'Moto'), ('Carro', 'Carro'), ('Caminhão', 'Caminhão')], max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=200)),
                ('Ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='C_servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Telefone', models.IntegerField()),
                ('CPF', models.IntegerField()),
                ('Email', models.CharField(max_length=150)),
                ('CEP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=150)),
                ('Qtd_estoque', models.IntegerField()),
                ('Cod_fabricante', models.IntegerField()),
                ('Nome_fabricante', models.IntegerField()),
                ('Valor_compra', models.DecimalField(decimal_places=2, max_digits=100)),
                ('Valor_venda', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='client',
            new_name='Cliente',
        ),
        migrations.CreateModel(
            name='manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Valor_total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('C_servicoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_servico', to='main.c_servico')),
                ('ClienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='main.cliente')),
                ('FuncionarioFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='main.funcionario')),
                ('ProdutoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produto', to='main.produto')),
                ('automovelFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automovel', to='main.automovel')),
            ],
        ),
    ]
