# Generated by Django 4.2.4 on 2023-10-04 00:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_automovel_c_servico_funcionario_produto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Boleto', 'Boleto'), ('CC', 'Cartão de credito'), ('CD', 'Cartão de debito')], max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('C', 'Cancelado')], default='P', max_length=100)),
                ('Desconto', models.DecimalField(decimal_places=2, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ManutencaoFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manutenção', to='main.manutencao')),
            ],
        ),
    ]
