# Generated by Django 4.2.4 on 2023-10-04 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('ClienteFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='main.cliente')),
            ],
        ),
    ]
