# Generated by Django 4.2.4 on 2023-10-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_automovel_data_c_servico_data_manutencao_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
