# Generated by Django 4.2.4 on 2023-10-08 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pagamento_valor_final_alter_manutencao_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='Desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
