# Generated by Django 4.2.4 on 2023-10-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_pagamento_desconto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='Data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='manutencaoFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manunteção_reserva', to='main.manutencao'),
        ),
    ]
