# Generated by Django 5.0.3 on 2024-04-05 01:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CAI', 'Aprendizagem Industrial'), ('CT', 'Curso Técnico'), ('CST', 'Curso Superior Técnico'), ('FIC', 'Formação continuada')], max_length=200)),
                ('duration', models.IntegerField()),
                ('durationType', models.CharField(choices=[('H', 'Horas'), ('S', 'Semetre')], max_length=100)),
                ('area', models.CharField(choices=[('TI', 'TI'), ('MEC', 'Mecatrônica'), ('ELÉTR', 'ELETRICISTA')], max_length=100)),
                ('modality', models.CharField(choices=[('EAD', 'Estudo a distancia'), ('P', 'Presencial'), ('H', 'Híbrido')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetDate', models.DateTimeField()),
                ('category', models.CharField(choices=[('CAI', 'Aprendizagem Industrial'), ('CT', 'Curso Técnico'), ('CST', 'Curso Superior Técnico'), ('FIC', 'Formação continuada')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block', models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timeLoad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrationNumber', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassDivison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Divisão_da_sala', to='app.class')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='courseFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Curso_da_Sala', to='app.courses'),
        ),
        migrations.CreateModel(
            name='CoursesThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tema_do_curso', to='app.courses')),
                ('themeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Temas', to='app.theme')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentAssingnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigneeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responsavel_do_ambiente', to=settings.AUTH_USER_MODEL)),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responsavel_ambientes_tarefas', to='app.environment')),
            ],
        ),
        migrations.CreateModel(
            name='Equipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
                ('assigneeFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Responsavel_equipamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Em Aprovamento'), ('3', 'Aprovado'), ('4', 'Em Revisão'), ('5', 'Cancelado')], default='1', max_length=100)),
                ('approverFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Aprovador', to=settings.AUTH_USER_MODEL)),
                ('coursesThemesFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tema_do_Curso', to='app.coursesthemes')),
                ('customuserFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano_do_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'Em Aprovamento'), ('3', 'Aprovado'), ('4', 'Em Revisão'), ('5', 'Cancelado')], max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=500)),
                ('file', models.CharField(max_length=10000)),
                ('planFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Status_plano', to='app.plan')),
            ],
        ),
        migrations.CreateModel(
            name='signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=200)),
                ('createdDate', models.DateField(auto_now_add=True)),
                ('customuserFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_do_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='signatureFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assinatura_do_plano', to='app.signatures'),
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('diagnostic', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(choices=[('M', 'Manuntenção'), ('ME', 'Melhoria')], max_length=100)),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em Andamento'), ('CA', 'Cancelada'), ('CO', 'Concluida'), ('EN', 'Encerrada')], max_length=30)),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ambientes_tarefas', to='app.environment')),
                ('repoterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responsavel_tarefas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigneeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responsavel_da_Tarefas', to=settings.AUTH_USER_MODEL)),
                ('taskFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reponsavel_pela_tarefa', to='app.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TasksEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipmentsFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento_da_tarefa', to='app.equipments')),
                ('taskFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tarefa_do_equipamento', to='app.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em Andamento'), ('CA', 'Cancelada'), ('CO', 'Concluida'), ('EN', 'Encerrada')], max_length=100)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=300)),
                ('taskFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tarefa_status', to='app.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='photosTasksStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100000)),
                ('type', models.CharField(choices=[('M', 'Manuntenção'), ('ME', 'Melhoria')], max_length=100)),
                ('fileType', models.CharField(choices=[('D', 'Documento'), ('F', 'foto')], max_length=100)),
                ('taskStatusFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_tarefa2', to='app.taskstatus')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('alocationStatus', models.CharField(choices=[('1', 'Rascunho'), ('2', 'Assinalado'), ('3', 'Concluido')], default='1', max_length=100)),
                ('classDivisionFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_dividida', to='app.classdivison')),
                ('customUserFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhe_ambiente_do_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocationDetailEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDay', models.CharField(max_length=100)),
                ('hourStart', models.TimeField()),
                ('hourEnd', models.TimeField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('environmentFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AMBIENTE_LOCAL_detalhado', to='app.environment')),
                ('teacherAlocationDetailFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Detalhe_do_ambiente_do_professor_detalhado', to='app.teacheralocationdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAlocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Classe_do_professor', to='app.class')),
                ('reporterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_relator', to=settings.AUTH_USER_MODEL)),
                ('themeFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Temas_do_professor', to='app.theme')),
            ],
        ),
    ]
