# Generated by Django 4.2.4 on 2023-08-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_characters_origin_alter_characters_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='episodes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.DateField(),
        ),
    ]
